<?php

return[
    'home' => 'Home',
    'informations' => 'Informations',
    'page_title' => 'Informations',

    'terms' => 'Terms of Use
    Version 2.0.1 Updated on 23/05/2021.
    The website TIDESCAPE - EXCLUSIVE MOMENTS, owned by ANM IT AND MANAGEMENT CONSULTING, UNIP LDA, VAT ID 513675400, hereinafter referred to as TIDESCAPE - EXCLUSIVE MOMENTS, with the website at www.tidescape.pt, is owned by TIDESCAPE - EXCLUSIVE MOMENTS. Certain features of the Site may be subject to additional guidelines, terms, or rules, which will be posted on the Site in connection with such features.
    All such terms, guidelines, and additional rules are incorporated by reference into these Terms.
    These Terms of Use describe the legally binding terms and conditions that oversee your use of the Site. By logging into the site, you are complying with these terms and affirming that you have authority and capacity to enter into these Terms. You must be at least 16 years old to access the site. IF YOU DO NOT AGREE WITH ALL PROVISIONS OF THESE TERMS, DO NOT LOG IN AND/OR USE THE SITE
    These terms require the use of arbitration Section 10.2 on an individual basis to resolve disputes and also limit the remedies available in the event of a dispute.

    Access to the site
    Subject to these Terms. The Company grants you a limited, non-transferable, non-exclusive, revocable, and non-sublicensable license to access the Site solely for your personal and non-commercial use.
    Certain restrictions. The rights approved to you in these Terms are subject to the following restrictions: (a) you shall not sell, rent, lease, transfer, assign, distribute, host, or exploit commercially the Site; (b) you shall not change, make derivative works, disassemble, compile or reverse engineer any part of the Site; (c) you shall not access the site to create a similar or competitive website; and (d) except as expressly stated herein, no part of the Site may be copied, reproduced, distributed, republished, downloaded, displayed, posted, or transmitted in any form or by any means unless otherwise indicated, any future release, update, or other addition to functionality of the Site shall be subject to these Terms. All copyright and other proprietary notices on the Site, must be retained on all copies.
    The Company reserves the right to change, suspend, or cease the Site with or without notice. You agree that the Company will not be held liable to you or any third-party for any change, interruption, or termination of the Site or any part thereof.
    No Support or Maintenance. You agree that the Company will have no obligation to provide you with any support related to the Site.
    Except for any User Content that you may provide, you are aware that all the intellectual property rights, including copyrights, patents, trademarks, and trade secrets, in the Site and its content are owned by the Company or the Company’s suppliers. Note that these Terms and access to the Site do not grant you any rights, title, or interest in or to any intellectual property rights, except for the limited access rights expressed in Section 2.1. The Company and its suppliers reserve all rights not granted in these Terms.

    Links and Third-Party Advertisements; Other Users
    Links and Third-Party Advertisements. The Site may contain links to third-party websites and/or display third-party advertisements. These Third-Party Links and Advertisements are not under the control of the Company, and the Company is not responsible for any Third-Party Links and Advertisements. The Company provides access to these Third-Party Links and Advertisements only as a convenience to you, and does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third-Party Links and Advertisements. You agree that you use all Third-Party Links and Advertisements at your own risk, and should apply a suitable level of caution and discretion in doing so. When you click on any of the Third-Party Links and Advertisements, the applicable third party’s terms and policies apply, including the third party’s privacy and data gathering practices.
    Other Users. Each user of the site is solely responsible for all and any user content. As we do not control User Content, you acknowledge and agree that we are not responsible for any User Content, provided by you or by third parties. You agree that the Company will not be responsible for any loss or damage incurred as the result of any such interactions. If there is a dispute between you and any site user, we have no obligation to get involved.
    By this, you forever release and discharge the Company and our directors, employees, agents, successors, and assigns and waive and waive any and all past, present, and future, disputes, claims, controversies, demands, rights, obligations, liabilities, actions, and causes of action of every kind and nature, that have arisen or arise directly or indirectly, or that relate directly or indirectly, to the Site.
    Cookies and Web Beacons. Like any other website, TIDESCAPE - EXCLUSIVE MOMENTS uses cookies. These cookies are used to store information, including visitors preferences, and the pages on the site that the visitor accessed or visited. The information is used to optimize users experience, customizing the content of our webpage based on visitors browser type and/or other information
    Our Advertising Partners. Some advertisers on our site may use cookies and web beacons. Our advertising partners are listed below. Each of our advertising partners has its own Privacy Policy for its user data policies. For easier access, we have provided links to the privacy policies below.
    • Google
    https://policies.google.com/technologies/ads

    Disclaimer
    The site is provided "as is" and "as available," and the company and our suppliers expressly disclaim all and any warranties and conditions of any kind, whether express, implied, or statutory, including all warranties or conditions of merchantability, fitness for a particular purpose, title, quiet enjoyment, accuracy, or non-infringement. We and our suppliers do not warrant that the site will meet your requirements, will be available uninterrupted, timely, secure, or error-free, or will be accurate, reliable, free of viruses or other harmful code, complete, legal, or safe. If applicable law requires any warranties with respect to the site, all such warranties are limited in duration to ninety (90) days from the date of first use.
    Some jurisdictions do not allow the exclusion of implied warranties; therefore, the exclusion above may not apply to you. Some jurisdictions do not allow limitations on how long an implied warranty lasts; therefore, the above limitation may not apply to you.

    Limitation of Liability
    To the fullest extent permitted by law, in no event will the company or our suppliers be liable to you or any third party for lost profits, lost data, costs of procurement of substitute products, or any indirect, consequential, exemplary, incidental, special, or punitive damages arising from or relating to these terms or your use or inability to use the site, even if the company has been advised of the possibility of such damages. Access to and use of the site is at your own discretion and risk, and you will be solely responsible for any damage to your device or computer system or loss of data resulting therefrom.
    You agree that our suppliers will have no liability of any kind arising from or relating to this agreement.
    Some jurisdictions do not allow the limitation or exclusion of liability for incidental or consequential damages; therefore, the above limitation or exclusion may not apply to you.
    Term and Termination. Subject to this Section, these Terms will remain in full force and effect while you use the Site. We may suspend or terminate your rights to use the Site at any time, for any reason, at our sole discretion, including for any use of the Site in violation of these Terms. Upon termination of your rights under these Terms, your Account and right to access and use the Site will terminate immediately. You understand that any termination of your account may involve the deletion of your User Content associated with your account from our active databases. The Company will not have any liability whatsoever to you for any termination of your rights under these Terms. Even after your rights under these Terms are terminated, the following provisions of these Terms will remain in effect: Sections 2 to 2.5, Section 3, and Sections 4 to 10.

    Copyright Policy.
    The company respects the intellectual property of others and asks that users of our site do the same. In connection with our site, we have adopted and implemented a policy respecting copyright law that provides for the removal of any infringing material and for the termination of users of our online site who are repeat infringers of intellectual property rights, including copyrights. If you believe that one of our users is, through the use of our Site, unlawfully infringing the copyright(s) in a work, and wish to have the allegedly infringing material removed, the following information in the form of a written notification must be provided to our designated copyright agent:
    •	Physical or electronic signature;
    •	Identification of the copyrighted work(s) that you claim to have been infringed;
    •	Identification of the material on our services that you claim is infringing and that you request us to remove;
    •	Sufficient information to permit us to locate that material;
    •	Your address, telephone number, and email address;
    •	A statement that you have a good faith belief that use of the objectionable material is not authorized by the copyright owner, its agent, or under the law; and
    •	A statement that the information in the notification is accurate, and, under penalty of perjury, that you are either the owner of the copyright that has allegedly been infringed or that you are authorized to act on behalf of the copyright owner.
    Any false claim of infringement relevant to this written notification automatically subjects the complaining party to liability for any damages, costs, and attorney’s fees incurred by us in connection with the written notification and allegation of copyright infringement.

    General
    These Terms are subject to occasional revisions and if we make substantial changes, we may notify you by sending you an e-mail to the last e-mail address you provided to us and/or by prominently posting notice of the changes on our Site. You are responsible for providing us with your most current e-mail address. In the event that the last e-mail address that you have provided us is not valid, our dispatch of the e-mail containing such notice will nonetheless constitute effective notice of the changes described in the notice. Any changes to these Terms will be effective upon the earliest of thirty (30) calendar days following our dispatch of an e-mail notice to you or thirty (30) calendar days following our posting of notice of the changes on our Site. These changes will be effective immediately for new users of our site. Your continued use of our site after such changes will indicate your acknowledgment of such changes and agreement to be bound by the terms and conditions of such changes. Dispute Resolution. Please read this Arbitration Agreement carefully. It is part of your contract with the Company and affects your rights. It contains procedures for MANDATORY BINDING ARBITRATION AND A CLASS ACTION WAIVER.

    Applicability of Arbitration Agreement. All claims and disputes in connection with the Terms or the use of any product or service provided by the Company that cannot be resolved informally or in small claims court shall be resolved by binding arbitration on an individual basis under the terms of this Arbitration Agreement. Unless otherwise agreed, all arbitration proceedings shall be conducted in English. This Arbitration Agreement applies to you and the Company, as well as to any subsidiaries, affiliates, agents, employees, predecessors in interest, successors, and assigns, as well as all authorized or unauthorized users or beneficiaries of services or goods provided under the Terms.
    Notice Requirement and Informal Dispute Resolution. Before either party may seek arbitration, the party must first send to the other party a written Notice of Dispute describing the nature and basis of the claim or dispute, and the requested relief. A Notice to the Company should be sent to: Tv. Vilar de Baixo, nº 288, 4475-507 – Maia, Portugal. After the Notice is received, you and the Company may attempt to resolve the claim or dispute informally. If you and the Company do not resolve the claim or dispute within thirty (30) days after the Notice is received, either party may begin an arbitration proceeding. The amount of any settlement offer made by any party may not be disclosed to the arbitrator until after the arbitrator has determined the amount of the award to which either party is entitled.
    Confidentiality. All aspects of the arbitration proceeding shall be strictly confidential. The parties agree to maintain confidentiality unless otherwise required by law. This paragraph shall not prevent a party from submitting to a court of law any information necessary to enforce this Agreement, to enforce an arbitration award, or to seek injunctive or equitable relief.
    Severability. If any part or parts of this Arbitration Agreement are found under the law to be invalid or unenforceable by a court of competent jurisdiction, then such specific part or parts shall be of no force and effect and shall be severed and the remainder of the Agreement shall continue in full force and effect.
    Right to Waive. Any or all of the rights and limitations set forth in this Arbitration Agreement may be waived by the party against whom the claim is asserted. Such waiver shall not waive or affect any other portion of this Arbitration Agreement.
    Survival of Agreement. This Arbitration Agreement will survive the termination of your relationship with the Company.
    Small Claims Court. Notwithstanding the foregoing, either you or the Company may bring an individual action in small claims court.
    Emergency Equitable Relief. Anyhow, the foregoing, either party may seek emergency equitable relief before a state or federal court to maintain the status quo pending arbitration. A request for interim measures shall not be deemed a waiver of any other rights or obligations under this Arbitration Agreement.
    Claims Not Subject to Arbitration. Notwithstanding the foregoing, claims of defamation, violation of the Computer Fraud and Abuse Act, and infringement or misappropriation of the other party’s patent, copyright, trademark, or trade secret shall not be subject to this Arbitration Agreement.
    Electronic Communications. Communications between you and the Company use electronic means, whether you use the Site or send us emails, or whether the Company posts notices on the Site or communicates with you via email. For contractual purposes, you (a) consent to receive communications from the Company in an electronic form; and (b) agree that all terms and conditions, agreements, notices, disclosures, and other communications that the Company provides to you electronically satisfy any legal obligation that such communications would satisfy if it were to be in writing. Complete Terms. These Terms constitute the entire agreement between you and us regarding the use of the Site. Our failure to exercise or enforce any right or provision of these Terms shall not operate as a waiver of such right or provision. The section titles in these Terms are for convenience only and have no legal or contractual effect. The word "including" means "including without limitation." If any provision of these Terms is, for any reason, held to be invalid or unenforceable, the other provisions of these Terms will be unimpaired and the invalid or unenforceable provision will be deemed modified so that it is valid and enforceable to the maximum extent permitted by law. Your relationship to the Company is that of an independent contractor, and neither party is an agent or partner of the other. These Terms, and your rights and obligations herein, may not be assigned, subcontracted, delegated, or otherwise transferred by you without the Company’s prior written consent, and any attempted assignment, subcontract, delegation, or transfer in violation of the foregoing will be null and void. The Company may freely assign these Terms. The terms and conditions set forth in these Terms shall be binding upon assignees.
    Copyright/Trademark Information. ’tidescape.pt’ & ‘tidescape.pt – Social Media Scheduler’ are two Copyright © registered trademarks and exclusive intellectual property of ANM IT & MANAGEMENT CONSULTING, UNIP LDA. All rights reserved. All trademarks, logos, and service marks displayed on the Site are our property or the property of other third-parties. You are not permitted to use these Marks without our prior written consent or the consent of such third party that may own the Marks.

    Contact Information
    Address: Porto (Headquarters)
    Praça da Pêdra Verde 217, 4100-385, Porto
    Email: legal@tidescape.pt',
];
