<?php

return[
    'home' => 'Inicio',
    'informations' => 'información',
    'page_title' => 'información',

    'terms' => 'Términos de Uso
    Versión 2.0.1 Actualizado el 23/05/2021.
    El sitio web TIDESCAPE - EXCLUSIVE MOMENTS, propiedad de ANM IT AND MANAGEMENT CONSULTING, UNIP LDA, NIF 513675400, en adelante denominado TIDESCAPE - EXCLUSIVE MOMENTS, con el sitio web en www.tidescape.pt, es propiedad de TIDESCAPE - EXCLUSIVE MOMENTS. Ciertas características del sitio pueden estar sujetas a pautas, términos o reglas adicionales, que se publicarán en el sitio en relación con esas características.
    Todos esos términos, pautas y reglas adicionales se incorporan por referencia a estos Términos.
    Estos Términos de Uso describen los términos y condiciones legalmente vinculantes que supervisan el uso del sitio. Al iniciar sesión en el sitio, estás cumpliendo con estos términos y afirmas tener la autoridad y capacidad para aceptar estos Términos. Debes tener al menos 16 años para acceder al sitio. SI NO ESTÁS DE ACUERDO CON TODAS LAS DISPOSICIONES DE ESTOS TÉRMINOS, NO INICIES SESIÓN Y/O NO USES EL SITIO.
    Estos términos requieren el uso de la Sección 10.2 de arbitraje de manera individual para resolver disputas y también limitan los recursos disponibles en caso de una disputa.

    Acceso al sitio
    Sujeto a estos Términos. La Empresa te otorga una licencia limitada, no transferible, no exclusiva, revocable y no sublicenciable para acceder al Sitio únicamente para uso personal y no comercial.
    Ciertas restricciones. Los derechos otorgados en estos Términos están sujetos a las siguientes restricciones: (a) no debes vender, alquilar, arrendar, transferir, asignar, distribuir, alojar o explotar comercialmente el Sitio; (b) no debes cambiar, crear obras derivadas, desmontar, compilar o realizar ingeniería inversa de ninguna parte del Sitio; (c) no debes acceder al sitio para crear un sitio web similar o competitivo; y (d) excepto según se indique expresamente en este documento, ninguna parte del Sitio puede copiarse, reproducirse, distribuirse, republicarse, descargarse, mostrarse, publicarse o transmitirse de ninguna manera o por ningún medio, salvo indicación en contrario, cualquier versión futura, actualización u otra adición a la funcionalidad del Sitio estará sujeta a estos Términos. Todos los derechos de autor y otros avisos de propiedad en el Sitio deben mantenerse en todas las copias.
    La Empresa se reserva el derecho de cambiar, suspender o interrumpir el Sitio con o sin previo aviso. Aceptas que la Empresa no será responsable ante ti o cualquier tercero por cualquier cambio, interrupción o terminación del Sitio o cualquier parte de este.
    Sin soporte o mantenimiento. Aceptas que la Empresa no tendrá ninguna obligación de brindarte soporte relacionado con el Sitio.
    Excepto por cualquier Contenido del Usuario que puedas proporcionar, eres consciente de que todos los derechos de propiedad intelectual, incluidos los derechos de autor, patentes, marcas comerciales y secretos comerciales, en el Sitio y su contenido son propiedad de la Empresa o de los proveedores de la Empresa. Ten en cuenta que estos Términos y el acceso al Sitio no te otorgan ningún derecho, título o interés o derechos de propiedad intelectual, excepto los derechos de acceso limitados expresados en la Sección 2.1. La Empresa y sus proveedores se reservan todos los derechos no otorgados en estos Términos.

    Enlaces y Anuncios de Terceros; Otros Usuarios
    Enlaces y Anuncios de Terceros. El Sitio puede contener enlaces a sitios web de terceros y/o mostrar anuncios de terceros. Estos Enlaces y Anuncios de Terceros no están bajo el control de la Empresa, y la Empresa no es responsable de ningún Enlace y Anuncio de Terceros. La Empresa proporciona acceso a estos Enlaces y Anuncios de Terceros solo como una conveniencia para ti, y no revisa, aprueba, supervisa, respalda, garantiza o hace representaciones con respecto a los Enlaces y Anuncios de Terceros. Aceptas que utilizas todos los Enlaces y Anuncios de Terceros bajo tu propio riesgo y debes aplicar un nivel adecuado de precaución y discreción al hacerlo. Cuando hagas clic en cualquiera de los Enlaces y Anuncios de Terceros, se aplicarán los términos y políticas del tercero correspondiente, incluidas las prácticas de privacidad y recopilación de datos del tercero.
    Otros Usuarios. Cada usuario del sitio es el único responsable de todo el Contenido del Usuario. Dado que no controlamos el Contenido del Usuario, reconoces y aceptas que no somos responsables de ningún Contenido del Usuario, ya sea proporcionado por ti o por terceros. Aceptas que la Empresa no será responsable de ninguna pérdida o daño incurrido como resultado de tales interacciones. Si hay una disputa entre tú y cualquier usuario del sitio, no tenemos la obligación de intervenir.
    Con esto, liberas de forma permanente y eximes a la Empresa y a nuestros directores, empleados, agentes, sucesores y cesionarios y renuncias a cualquier disputa, reclamación, controversia, demanda, derechos, obligaciones, responsabilidades, acciones y causas de acción de cualquier tipo y naturaleza, que hayan surgido o surjan directa o indirectamente, o que estén relacionadas directa o indirectamente, con el Sitio.
    Cookies y Web Beacons. Al igual que cualquier otro sitio web, TIDESCAPE - EXCLUSIVE MOMENTS utiliza cookies. Estas cookies se utilizan para almacenar información, incluidas las preferencias de los visitantes y las páginas del sitio que el visitante ha accedido o visitado. La información se utiliza para optimizar la experiencia de los usuarios, personalizando el contenido de nuestra página web según el tipo de navegador y/o otra información de los visitantes.
    Nuestros Socios Publicitarios. Algunos anunciantes en nuestro sitio pueden usar cookies y web beacons. Nuestros socios publicitarios se enumeran a continuación. Cada uno de nuestros socios publicitarios tiene su propia Política de Privacidad para sus políticas de datos de usuario. Para facilitar el acceso, hemos proporcionado enlaces a las políticas de privacidad a continuación.
    • Google
    https://policies.google.com/technologies/ads

    Descargo de responsabilidad
    El sitio se proporciona "tal cual" y "según disponibilidad", y la empresa y nuestros proveedores renuncian expresamente a todas y cada una de las garantías y condiciones de cualquier tipo, ya sea expresa, implícita o legal, incluidas todas las garantías o condiciones de comerciabilidad, idoneidad para un propósito particular, título, disfrute tranquilo, exactitud o no infracción. Nosotros y nuestros proveedores no garantizamos que el sitio satisfará tus requisitos, estará disponible de manera ininterrumpida, oportuna, segura o libre de errores, o será exacto, confiable, libre de virus u otro código perjudicial, completo, legal o seguro. Si la ley aplicable exige alguna garantía con respecto al sitio, todas esas garantías estarán limitadas en duración a noventa (90) días a partir de la fecha del primer uso.
    Algunas jurisdicciones no permiten la exclusión de garantías implícitas; por lo tanto, la exclusión anterior puede no aplicarse a ti. Algunas jurisdicciones no permiten limitaciones sobre cuánto tiempo dura una garantía implícita; por lo tanto, la limitación anterior puede no aplicarse a ti.

    Limitación de responsabilidad
    En la máxima medida permitida por la ley, en ningún caso la empresa ni nuestros proveedores serán responsables ante ti o cualquier tercero por lucro cesante, pérdida de datos, costos de adquisición de productos de reemplazo o cualquier daño indirecto, consecuente, ejemplar, incidental, especial o punitivo que surja de o esté relacionado con estos términos o tu uso o incapacidad para usar el sitio, incluso si la empresa ha sido informada de la posibilidad de tales daños. El acceso y uso del sitio son a tu propia discreción y riesgo, y serás el único responsable de cualquier daño a tu dispositivo o sistema informático o pérdida de datos que resulte de ello.
    Aceptas que nuestros proveedores no tendrán responsabilidad de ningún tipo derivada de o relacionada con este acuerdo.
    Algunas jurisdicciones no permiten la limitación o exclusión de responsabilidad por daños incidentales o consecuentes; por lo tanto, la limitación o exclusión anterior puede no aplicarse a ti.
    Plazo y terminación. Sujeto a esta Sección, estos Términos permanecerán en pleno vigor y efecto mientras uses el Sitio. Podemos suspender o terminar tus derechos de uso del Sitio en cualquier momento, por cualquier motivo, a nuestra sola discreción, incluido cualquier uso del Sitio en violación de estos Términos. Al finalizar tus derechos bajo estos Términos, tu cuenta y tu derecho de acceder y usar el Sitio terminarán de inmediato. Entiendes que cualquier terminación de tu cuenta puede implicar la eliminación del Contenido del Usuario asociado con tu cuenta de nuestras bases de datos activas. La Empresa no tendrá ninguna responsabilidad ante ti por cualquier terminación de tus derechos bajo estos Términos. Incluso después de que tus derechos bajo estos Términos se hayan terminado, las siguientes disposiciones de estos Términos seguirán vigentes: Secciones 2 a 2.5, Sección 3 y Secciones 4 a 10.

    Política de derechos de autor.
    La empresa respeta la propiedad intelectual de los demás y solicita que los usuarios de nuestro sitio hagan lo mismo. En relación con nuestro sitio, hemos adoptado e implementado una política que respeta la ley de derechos de autor, que prevé la eliminación de cualquier material infractor y la terminación de los usuarios de nuestro sitio en línea que son infractores habituales de los derechos de propiedad intelectual, incluidos los derechos de autor. Si crees que uno de nuestros usuarios, a través del uso de nuestro sitio, infringe ilícitamente los derechos de autor de un trabajo y deseas que se elimine el material supuestamente infractor, debes proporcionar la siguiente información en forma de una notificación escrita a nuestro agente designado de derechos de autor:
    • Firma física o electrónica;
    • Identificación de la obra(s) con derechos de autor que afirmas que ha sido infringida;
    • Identificación del material en nuestros servicios que afirmas que es infractor y que solicitas que eliminemos;
    • Suficiente información para permitirnos localizar ese material;
    • Tu dirección, número de teléfono y dirección de correo electrónico;
    • Una declaración de que tienes una creencia de buena fe de que el uso del material objetable no está autorizado por el propietario de los derechos de autor, su agente o por la ley; y
    • Una declaración de que la información en la notificación es precisa y, bajo pena de perjurio, eres el propietario del copyright que supuestamente ha sido infringido o que estás autorizado para actuar en nombre del propietario del copyright.
    Cualquier reclamación falsa de infracción relevante para esta notificación escrita sujeta automáticamente a la parte que presenta la queja a la responsabilidad por cualquier daño, costo y honorarios de abogados incurridos por nosotros en relación con la notificación escrita y la alegación de infracción de derechos de autor.

    General
    Estos Términos están sujetos a revisiones ocasionales y, si realizamos cambios sustanciales, podemos notificarte enviándote un correo electrónico a la última dirección de correo electrónico que nos proporcionaste y/o mediante la publicación destacada de un aviso de los cambios en nuestro Sitio. Eres responsable de proporcionarnos tu dirección de correo electrónico más actualizada. En caso de que la última dirección de correo electrónico que nos hayas proporcionado no sea válida, el envío del correo electrónico que contenga dicho aviso seguirá constituyendo un aviso efectivo de los cambios descritos en el aviso. Cualquier cambio en estos Términos será efectivo en la fecha más temprana de treinta (30) días calendario después de que enviemos un aviso por correo electrónico o treinta (30) días calendario después de que publiquemos un aviso de los cambios en nuestro Sitio. Estos cambios serán efectivos de inmediato para los nuevos usuarios de nuestro sitio. Tu uso continuado de nuestro sitio después de tales cambios indicará tu reconocimiento de dichos cambios y tu acuerdo de estar sujeto a los términos y condiciones de dichos cambios. Resolución de disputas. Lee con atención este Acuerdo de Arbitraje. Es parte de tu contrato con la Empresa y afecta tus derechos. Contiene procedimientos para el ARBITRAJE OBLIGATORIO Y UNA RENUNCIA A ACCIONES COLECTIVAS.

    Aplicabilidad del Acuerdo de Arbitraje. Todas las reclamaciones y disputas en relación con los Términos o el uso de cualquier producto o servicio proporcionado por la Empresa que no puedan resolverse de manera informal o en un tribunal de reclamaciones menores se resolverán mediante arbitraje vinculante de manera individual bajo los términos de este Acuerdo de Arbitraje. A menos que se acuerde lo contrario, todas las actuaciones arbitrales se llevarán a cabo en inglés. Este Acuerdo de Arbitraje se aplica a ti y a la Empresa, así como a cualquier subsidiaria, afiliada, agente, empleado, predecesores en interés, sucesores y cesionarios, así como a todos los usuarios autorizados o no autorizados o beneficiarios de servicios o bienes proporcionados bajo los Términos.
    Requisito de notificación y resolución informal de disputas. Antes de que cualquiera de las partes pueda buscar arbitraje, la parte debe enviar primero a la otra parte un Aviso de Disputa por escrito que describa la naturaleza y base de la reclamación o disputa, y el alivio solicitado. Un Aviso a la Empresa debe enviarse a: Tv. Vilar de Baixo, nº 288, 4475-507 – Maia, Portugal. Después de recibir el Aviso, tú y la Empresa pueden intentar resolver la reclamación o disputa de manera informal. Si tú y la Empresa no resuelven la reclamación o disputa dentro de los treinta (30) días después de recibir el Aviso, cualquiera de las partes puede iniciar un procedimiento de arbitraje. La cantidad de cualquier oferta de liquidación realizada por cualquiera de las partes no se divulgará al árbitro hasta después de que el árbitro haya determinado la cantidad del premio a la que tiene derecho cualquiera de las partes.
    Confidencialidad. Todos los aspectos del procedimiento arbitral serán estrictamente confidenciales. Las partes acuerdan mantener la confidencialidad a menos que la ley requiera lo contrario. Este párrafo no evitará que una de las partes presente ante un tribunal de justicia cualquier información necesaria para hacer cumplir este Acuerdo, hacer cumplir un laudo arbitral o buscar medidas cautelares o equitativas.
    Separabilidad. Si alguna parte o partes de este Acuerdo de Arbitraje se consideran inválidas o inaplicables según la ley por un tribunal de jurisdicción competente, esa parte o partes específicas no tendrán fuerza y ​​efecto y serán anuladas, y el resto del Acuerdo continuará en pleno vigor y efecto.
    Derecho a renunciar. Cualquiera o todos los derechos y limitaciones establecidos en este Acuerdo de Arbitraje pueden ser renunciados por la parte contra la cual se presenta la reclamación. Dicha renuncia no renunciará ni afectará ninguna otra parte de este Acuerdo de Arbitraje.
    Supervivencia del Acuerdo. Este Acuerdo de Arbitraje sobrevivirá a la terminación de tu relación con la Empresa.
    Tribunal de reclamaciones menores. No obstante lo anterior, tú o la Empresa pueden presentar una acción individual en un tribunal de reclamaciones menores.
    Medidas cautelares de emergencia. Sin perjuicio de lo anterior, cualquiera de las partes puede buscar medidas cautelares de emergencia ante un tribunal estatal o federal para mantener el estado actual en espera del arbitraje. Una solicitud de medidas provisionales no se considerará una renuncia a ningún otro derecho u obligación en virtud de este Acuerdo de Arbitraje.
    Reclamaciones no sujetas a arbitraje. No obstante lo anterior, las reclamaciones de difamación, violación de la Ley de Fraude y Abuso Informático, e infracción o apropiación indebida de la patente, copyright, marca comercial o secreto comercial de la otra parte no estarán sujetas a este Acuerdo de Arbitraje.
    Comunicaciones electrónicas. Las comunicaciones entre tú y la Empresa utilizan medios electrónicos, ya sea que utilices el Sitio o nos envíes correos electrónicos, o ya sea que la Empresa publique avisos en el Sitio o se comunique contigo por correo electrónico. A efectos contractuales, (a) consientes en recibir comunicaciones de la Empresa en forma electrónica; y (b) aceptas que todos los términos y condiciones, acuerdos, avisos, divulgaciones y otras comunicaciones que la Empresa te proporcione electrónicamente cumplen con cualquier obligación legal que dichas comunicaciones cumplirían si estuvieran por escrito. Términos completos. Estos Términos constituyen el acuerdo completo entre tú y nosotros con respecto al uso del Sitio. Nuestra falta de ejercicio o aplicación de cualquier derecho o disposición de estos Términos no constituirá una renuncia a tal derecho o disposición. Los títulos de las secciones en estos Términos son solo para conveniencia y no tienen ningún efecto legal o contractual. La palabra "incluyendo" significa "incluyendo pero no limitado a". Si alguna disposición de estos Términos se considera, por cualquier motivo, inválida o inaplicable, las demás disposiciones de estos Términos no se verán afectadas y la disposición inválida o inaplicable se considerará modificada para que sea válida y aplicable en la medida máxima permitida por la ley. Tu relación con la Empresa es la de un contratista independiente, y ninguna de las partes es un agente o socio de la otra. Estos Términos, y tus derechos y obligaciones en virtud de estos, no pueden ser cedidos, subcontratados, delegados ni transferidos de ninguna otra manera por ti sin el consentimiento previo por escrito de la Empresa, y cualquier intento de asignación, subcontratación, delegación o transferencia en violación de lo anterior será nulo y sin valor. La Empresa puede asignar libremente estos Términos. Los términos y condiciones establecidos en estos Términos serán vinculantes para los cesionarios.
    Informações de Direitos Autorais/Marcas Registradas. ’tidescape.pt’ e ‘tidescape.pt – Social Media Scheduler’ são duas marcas registradas de direitos autorais © e propriedade intelectual exclusiva da ANM IT AND MANAGEMENT CONSULTING, UNIP LDA. Todos os direitos reservados. Todas as marcas registradas, logotipos e marcas de serviço exibidos no site são de nossa propriedade ou propriedade de terceiros. Você não está autorizado a usar essas marcas sem nosso consentimento prévio por escrito ou o consentimento de terceiros que possam ser proprietários das marcas.

    Informações de Contato
    Endereço: Porto (Sede)
    Praça da Pêdra Verde 217, 4100-385, Porto
    Email: legal@tidescape.pt'
];
