<?php

return [
    'home' => 'Início',
    'informations' => 'Informações',
    'page_title' => 'Informações',

    'terms' => 'Termos de Uso do Site
    Versão 2.0.1 Atualizado a 23/05/2021.
    O site TIDESCAPE - EXCLUSIVE MOMENTS, propriedade pertencente a ANM IT AND MANAGEMENT CONSULTING, UNIP LDA, NIF 513675400, adiante designado por TIDESCAPE - EXCLUSIVE MOMENTS, com site em www.tidescape.pt, é propriedade pertencente à TIDESCAPE - EXCLUSIVE MOMENTS. Certos recursos do Site podem estar sujeitos a diretrizes, termos ou regras adicionais, que serão publicados no Site em conexão com esses recursos.
    Todos esses termos, diretrizes e regras adicionais são incorporados por referência a estes Termos.
    Estes Termos de Uso descrevem os termos e condições juridicamente vinculativos que supervisionam o uso do Site. Ao fazer login no site, está a cumprir estes termos e declara ter autoridade e capacidade para celebrar estes Termos. Deve ter pelo menos 16 anos de idade para aceder o site. SE NÃO CONCORDAR COM TODAS AS DISPOSIÇÕES DESTES TERMOS, NÃO FAÇA LOGIN E / OU USE O SITE
    Esses termos exigem o uso da Seção 10.2 de arbitragem individualmente para resolver disputas e também limitam os recursos disponíveis no caso de uma disputa.

    Acesso ao site
    Sujeito a estes Termos. A Empresa concede-lhe uma licença limitada intransferível, não exclusiva, revogável e revogável para acessar o Site apenas para seu uso pessoal e não comercial.
    Certas restrições. Os direitos aprovados nestes Termos estão sujeitos às seguintes restrições: (a) não deve vender, alugar, arrendar, transferir, atribuir, distribuir, hospedar ou explorar comercialmente o Site; (b) não deve alterar, fazer trabalhos derivados, desmontar, compilar ou fazer engenharia reversa de qualquer parte do Site; (c) não deve acessar o site para criar um site semelhante ou competitivo; e (d) exceto conforme expressamente indicado neste documento, nenhuma parte do Site pode ser copiada, reproduzida, distribuída, republicada, baixada, exibida, postada ou transmitida de qualquer forma ou por qualquer meio, salvo indicação em contrário, qualquer versão futura, atualização ou outra adição à funcionalidade do Site estará sujeita a estes Termos. Todos os direitos autorais e outros avisos de propriedade no Site, devem ser mantidos em todas as cópias.
    A Empresa reserva-se o direito de alterar, suspender ou interromper o Site com ou sem aviso prévio.  Aprova que a Empresa não será responsabilizada por si ou por terceiros por qualquer alteração, interrupção ou rescisão do Site ou de qualquer parte.
    Sem suporte ou manutenção. Concorda que a Empresa não terá nenhuma obrigação de fornecer-lhe qualquer suporte relacionado ao Site.
    Excluindo qualquer Conteúdo do Usuário que possa fornecer, está ciente de que todos os direitos de propriedade intelectual, incluindo direitos autorais, patentes, marcas comerciais e segredos comerciais, no Site e seu conteúdo pertencem à Empresa ou aos fornecedores da Empresa. Observe que estes Termos e acesso ao Site não lhe concedem nenhum direito, título ou interesse ou direitos de propriedade intelectual, exceto os direitos de acesso limitados expressos na Seção 2.1. A Empresa e os seus fornecedores reservam todos os direitos não concedidos nestes Termos.

    Links e anúncios de terceiros; Outros usuários
    Links e anúncios de terceiros. O Site pode conter links para sites e serviços de terceiros e / ou exibir anúncios de terceiros. Esses Links e Anúncios de Terceiros não estão sob o controle da Empresa, e a Empresa não é responsável por quaisquer Links e Anúncios de Terceiros. A Empresa fornece acesso a esses Links e anúncios de terceiros apenas como uma conveniência para si, e não analisa, aprova, monitora, endossa, garante, ou faz quaisquer representações em relação aos Links e anúncios de terceiros. Concorda que usa todos os Links e anúncios de terceiros por seu próprio risco e deve aplicar um nível adequado de cautela e discrição ao fazê-lo. Quando clica em qualquer um dos Links e anúncios de terceiros, os termos e políticas de terceiros aplicáveis são aplicáveis, incluindo as práticas de privacidade e coleta de dados de terceiros.
    Outros usuários. Cada usuário do site é o único responsável por todo e qualquer conteúdo do usuário. Como não controlamos o Conteúdo do Usuário, reconhece e concorda que não somos responsáveis por nenhum Conteúdo do Usuário, fornecido por si ou por terceiros. Concorda que a Empresa não será responsável por qualquer perda ou dano incorrido como resultado de tais interações. Se houver uma disputa entre si e qualquer usuário do site, não temos obrigação de nos envolver.
    Por meio deste, libera e exonera para sempre a Empresa e nossos diretores, funcionários, agentes, sucessores e cessionários e renuncia e renuncia a todo e qualquer conflito passado, presente e futuro, reclamação, controvérsia, demanda, direito, obrigação, responsabilidade, ação e causa de ação de todo tipo e natureza, que surgiu ou surge direta ou indiretamente, ou que se relaciona direta ou indiretamente com o Site.
    Cookies e Web Beacons. Como qualquer outro site, TIDESCAPE - EXCLUSIVE MOMENTS usa cookies. Esses cookies são usados para armazenar informações, incluindo as preferências dos visitantes, e as páginas no site que o visitante entrou ou visitou. As informações são usadas para otimizar a experiência dos usuários, personalizando o conteúdo de nossa página da web com base no tipo de navegador dos visitantes e / ou outras informações.
    Nossos parceiros de publicidade. Alguns anunciantes em nosso site podem usar cookies e web beacons. Nossos parceiros de publicidade estão listados abaixo. Cada um de nossos parceiros de publicidade possui sua própria Política de Privacidade para suas políticas de dados do usuário. Para um acesso mais fácil, criamos um link para as políticas de privacidade abaixo.
    •	Google
    https://policies.google.com/technologies/ads

    Isenções de responsabilidade
    O site é fornecido "no estado em que se encontra" e "conforme disponível", e a empresa e nossos fornecedores renunciam expressamente a todas e quaisquer garantias e condições de qualquer tipo, expressas, implícitas ou estatutárias, incluindo todas as garantias ou condições de comercialização , adequação a uma finalidade específica, título, diversão tranquila, precisão ou não violação. Nós e nossos fornecedores não garantimos que o site atenda aos seus requisitos, esteja disponível de forma ininterrupta, oportuna, segura ou sem erros, ou seja preciso, confiável, livre de vírus ou outro código nocivo, completo, legal ou seguro. Se a lei aplicável exigir garantias em relação ao site, todas essas garantias terão uma duração limitada a noventa (90) dias a partir da data do primeiro uso.
    Algumas jurisdições não permitem a exclusão de garantias implícitas; portanto, a exclusão acima pode não se aplicar a si. Algumas jurisdições não permitem limitações quanto à duração de uma garantia implícita; portanto, a limitação acima pode não se aplicar a si.

    Limitação de responsabilidade
    Na extensão máxima permitida por lei, em nenhum caso a empresa ou nossos fornecedores serão responsáveis perante si ou terceiros por lucros cessantes, dados perdidos, custos de aquisição de produtos substitutos ou quaisquer indiretos, consequentes, exemplares, incidentais, danos especiais ou punitivos decorrentes ou relacionados a estes termos ou ao seu uso ou incapacidade de usar o site, mesmo que a empresa tenha sido avisada da possibilidade de tais danos. O acesso e o uso do site são por sua conta e risco, e você será o único responsável por qualquer dano ao seu dispositivo ou sistema de computador ou perda de dados resultantes.
    Concorda que nossos fornecedores não terão nenhuma responsabilidade de qualquer tipo resultante ou relacionada a este contrato.
    Algumas jurisdições não permitem a limitação ou exclusão de responsabilidade por danos incidentais ou consequenciais; portanto, a limitação ou exclusão acima pode não se aplicar a si.
    Prazo e Rescisão. Sujeitos a esta Seção, estes Termos permanecerão em pleno vigor e efeito enquanto usar o Site. Podemos suspender ou rescindir seus direitos de usar o Site a qualquer momento, por qualquer motivo, a nosso critério, inclusive por qualquer uso do Site em violação a estes Termos. Após a rescisão de seus direitos sob estes Termos, sua Conta e o direito de acessar e usar o Site serão encerrados imediatamente. Você entende que qualquer rescisão da sua conta pode envolver a exclusão do conteúdo do usuário associado à sua conta de nossos bancos de dados ativos. A Empresa não se responsabilizará por qualquer rescisão de seus direitos sob estes Termos. Mesmo depois que seus direitos sob estes Termos forem rescindidos, as seguintes disposições destes Termos permanecerão em vigor: Seções 2 a 2.5, Seção 3 e Seções 4 a 10.

    Política de direitos autorais.
    A empresa respeita a propriedade intelectual de terceiros e solicita que os usuários do nosso site façam o mesmo. Em conexão com o nosso site, adotamos e implementamos uma política respeitando a lei de direitos autorais que prevê a remoção de qualquer material infrator e o encerramento de usuários do nosso site on-line que violam repetidamente os direitos de propriedade intelectual, incluindo direitos autorais. Se acredita que um de nossos usuários está, através do uso do nosso Site, infringindo ilegalmente os direitos autorais de uma obra e deseja remover o material supostamente infrator, as seguintes informações na forma de uma notificação por escrito devem ser fornecidas ao nosso Agente de direitos autorais designado:
    •	Assinatura física ou eletrónica;
    •	Identificação do (s) trabalho (s) protegido por direitos autorais que alega ter sido violado;
    •	Identificação do material em nossos serviços que alega estar infringindo e que você solicita a remoção;
    •	Informações suficientes para nos permitir localizar esse material;
    •	O seu endereço, número de telefone, e endereço de e-mail;
    •	Uma declaração de que acredita de boa fé que o uso do material censurável não está autorizado pelo proprietário dos direitos autorais, por seu agente ou por lei; e
    •	Uma declaração de que as informações na notificação são precisas e, sob pena de perjúrio, que é o proprietário dos direitos autorais que supostamente foram violados ou que está autorizado a agir em nome do proprietário dos direitos autorais.
    Qualquer declaração falsa de fato relevante em uma notificação por escrito sujeita automaticamente a parte reclamante à responsabilidade por quaisquer danos, custos e honorários advocatórios incorridos por nós em conexão com a notificação por escrito e alegação de violação de direitos autorais.

    Geral
    Estes Termos estão sujeitos a revisões ocasionais e, se fizermos alterações substanciais, poderemos notificá-lo enviando um e-mail para o último endereço de e-mail que nos forneceu e / ou publicando com destaque as alterações em nosso site. Local. Você é responsável por nos fornecer seu endereço de e-mail mais atual. Caso o último endereço de e-mail que nos forneceu não seja válido, nosso envio do e-mail que contém esse aviso constituirá, no entanto, um aviso efetivo das alterações descritas no aviso. Quaisquer alterações nestes Termos entrarão em vigor no prazo de trinta (30) dias corridos após o envio de um aviso por e-mail para si ou trinta (30) dias corridos após a publicação do aviso das alterações em nosso Site. Essas alterações entrarão em vigor imediatamente para novos usuários do nosso site. O uso continuado do nosso site após o aviso de tais alterações indicará que reconhece essas alterações e concorda em estar vinculado aos termos e condições de tais alterações. Resolução de disputas. Por favor, leia este Contrato de Arbitragem com atenção. Faz parte do seu contrato com a Empresa e afeta seus direitos. Ele contém procedimentos para ARBITRAGEM OBRIGATÓRIA DE LIGAÇÃO E UMA ISENÇÃO DE AÇÃO DE CLASSE.

    Aplicabilidade do Contrato de Arbitragem. Todas as reclamações e disputas relacionadas aos Termos ou o uso de qualquer produto ou serviço fornecido pela Empresa que não possa ser resolvido informalmente ou em um tribunal de pequenas causas serão resolvidas por arbitragem vinculativa em base individual, nos termos deste Contrato de Arbitragem. Salvo acordo em contrário, todos os procedimentos de arbitragem serão realizados em inglês. Este Contrato de Arbitragem se aplica a você e à Empresa, bem como a quaisquer subsidiárias, afiliadas, agentes, funcionários, predecessores de interesses, sucessores e cessionários, bem como todos os usuários ou beneficiários autorizados ou não autorizados de serviços ou bens fornecidos sob os Termos.
    Requisito de aviso e resolução informal de disputas. Antes que uma das partes possa solicitar a arbitragem, a parte deve primeiro enviar à outra parte um Aviso de Disputa por escrito descrevendo a natureza e a base da reivindicação ou disputa, e o alívio solicitado. Um Aviso para a empresa devem ser enviados para: Tv. Vilar de Baixo, nº 288, 4475-507 – Maia, Portugal. Após o recebimento do Aviso, você e a Empresa podem tentar resolver a reivindicação ou disputa informalmente. Se você e a Empresa não resolverem a reclamação ou disputa dentro de trinta (30) dias após o recebimento do Aviso, qualquer uma das partes poderá iniciar um processo de arbitragem. O valor de qualquer oferta de liquidação feita por qualquer parte não poderá ser divulgado ao árbitro até que o árbitro tenha determinado o valor da sentença a que uma das partes tem direito.
    Confidencialidade. Todos os aspetos do processo de arbitragem devem ser estritamente confidenciais. As partes concordam em manter a confidencialidade, a menos que exigido por lei. Este parágrafo não impedirá que uma parte submeta a um tribunal qualquer informação necessária para fazer cumprir este Contrato, fazer cumprir uma sentença arbitral ou buscar uma medida cautelar ou equitativa.
    Divisibilidade. Se qualquer parte ou parte deste Contrato de Arbitragem for considerada inválida ou inexequível por um tribunal de jurisdição competente, essa parte ou partes específicas não terão força e efeito e serão cortadas, e o restante do Contrato será continue com força total e efeito.
    Direito de renúncia. Qualquer um ou todos os direitos e limitações estabelecidos neste Contrato de Arbitragem podem ser renunciados pela parte contra a qual a reivindicação é reivindicada. Essa renúncia não renuncia ou afeta qualquer outra parte deste Contrato de Arbitragem.
    Sobrevivência do acordo. Este Contrato de Arbitragem sobreviverá ao término do seu relacionamento com a Empresa.
    Tribunal de Pequenas Causas. Não obstante, o acima exposto, você ou a Empresa podem intentar uma ação individual no tribunal de pequenas causas.
    Alívio Equitativo de Emergência. De qualquer forma, o que precede, qualquer uma das partes pode buscar uma solução equitativa de emergência perante um tribunal estadual ou federal para manter o status quo na arbitragem. Um pedido de medidas provisórias não será considerado uma renúncia a quaisquer outros direitos ou obrigações sob este Contrato de Arbitragem.
    Reivindicações não sujeitas a arbitragem. Não obstante o acima exposto, reivindicações de difamação, violação da Lei de fraude e abuso de computador e violação ou apropriação indevida da patente, direitos autorais, marca comercial ou segredos comerciais da outra parte não estarão sujeitas a este Acordo de Arbitragem.
    Comunicações Eletrónicas. As comunicações entre si e a Empresa usam meios eletrônicos, se usa o Site ou nos envia e-mails, ou se a Empresa publica avisos no Site ou se comunica consigo por e-mail. Para fins contratuais, consente em receber comunicações da Empresa em formato eletrónico; e (b) concorda que todos os termos e condições, acordos, avisos, divulgações e outras comunicações que a Empresa fornece, cumprem eletronicamente qualquer obrigação legal que estas comunicações cumpririam se estivessem em cópia impressa.
    Termos completos. Estes Termos constituem o contrato completo entre si e nós em relação ao uso do Site. Nossa falha em exercer ou fazer cumprir qualquer direito ou disposição destes Termos não deve funcionar como uma renúncia a esse direito ou disposição. Os títulos das seções nestes Termos são apenas para conveniência e não têm efeito legal ou contratual. A palavra "incluindo" significa "incluindo sem limitação". Se qualquer cláusula destes Termos for considerada inválida ou inexequível, as outras cláusulas destes Termos não serão afetadas e a cláusula inválida ou inexequível será considerada modificada para que seja válida e exequível na extensão máxima permitida por lei. Seu relacionamento com a empresa é de um contratado independente e nenhuma das partes é agente ou parceiro da outra. Estes Termos, e seus direitos e obrigações aqui contidos, não podem ser cedidos, subcontratados, delegados ou transferidos por si sem o consentimento prévio por escrito da Empresa, e qualquer tentativa de cessão, subcontrato, delegação ou transferência que viole o exposto acima será nula e vazio. A Empresa pode atribuir livremente estes Termos. Os termos e condições estabelecidos nestes Termos serão vinculativos para os cessionários.
    Informações sobre direitos autorais / marca comercial. ’tidescape.pt’ & ‘tidescape.pt – Social Media Scheduler’ são duas marcas Copyright © devidamente registadas e propriedade intelectual exclusiva de ANM IT & MANAGEMENT CONSULTING, UNIP LDA. Todos os direitos são reservados. Todas as marcas comerciais, logotipos e marcas de serviço exibidas no Site são de nossa propriedade ou de terceiros. Não tem permissão para usar estas Marcas sem o nosso consentimento prévio por escrito ou com o consentimento de terceiros que possam ser proprietários das Marcas.

    Informações para contato
    Endereço: Porto (Sede)
    Praça da Pêdra Verde 217, 4100-385, Porto
    E-mail: legal@tidescape.pt',
];
